name: pixel_retro_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  get: ^4.7.2
  get_it: ^8.2.0
  go_router: ^16.2.0
  google_mobile_ads: ^6.0.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.5.3
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/gifs/
    - assets/images/
    - assets/icons/
    - assets/icons/trophies/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_24pt-Light.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_24pt-Regular.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_24pt-Bold.ttf
          weight: 700
    - family: Pixel
      fonts:
        - asset: assets/fonts/pixel/PixelifySans-Regular.ttf
          weight: 500
        - asset: assets/fonts/pixel/PixelifySans-Medium.ttf
          weight: 600
        - asset: assets/fonts/pixel/PixelifySans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/pixel/PixelifySans-Bold.ttf
          weight: 800
    - family: Noto
      fonts:
        - asset: assets/fonts/noto/NotoColorEmoji-Regular.ttf
          weight: 700
